# Generated by Django 4.0 on 2022-02-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.FileField(upload_to='document/users/profile/')),
            ],
            options={
                'db_table': 'users_profile',
            },
        ),
    ]
